kind: pipeline
type: docker
name: mod-api-dev-parallel

trigger:
  branch:
    - develop
  event:
    - pull_request
    - push
concurrency:
  limit: 1
  
steps:

  # Clean agent images and containers to prevent disk space overuse
  - name: echo test
    image: docker:19.03.11-git
    commands:
      - echo 'test'
